music/urls.py
from django.urls import path

from . import views

#  app_name used for Namespace 

app_name = 'music'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('<int:pk>/', views.AlbumDetail.as_view(), name='detail'),

    path('album/add/', views.AlbumCreate.as_view(), name='album_create'),

    path('album/edit/<int:pk>/', views.AlbumUpdate.as_view(), name='album_update'),

    path('album/delete/<int:pk>/', views.AlbumDelete.as_view(), name='album_delete'),


    


]

musicwebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('',views.index),
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),

]

music/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

   
    def __str__(self):

        return self.artist
    
    
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})
    


class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)    
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=250)  
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

















































     





        
    
    

music/views.py
# from django.shortcuts import render,get_object_or_404
from .models import Album, Song
from django.urls import reverse_lazy
# from django.core.urlresolvers import reverse_lazy
# Create your views here
# from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView

class IndexView(ListView):

    template_name = "music/index.html"
    context_object_name = "latest_album_list"

    def get_queryset(self):
        return Album.objects.all()



class AlbumDetail(DetailView):

    model = Album

    context_object_name = "album_details"

    template_name= "music/detail.html"


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']


class AlbumCrete(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']




class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']
    template_name_suffix = '_update_form'




class AlbumDelete(DeleteView):
    model = Album
    # success_url = "/music/"
    success_url = reverse_lazy("music:index")







# def index(request):
#     latest_album_list = Album.objects.all()
#     hello = "Hello World! Pass Data to View for Display"
#     context = {'latest_album_list': latest_album_list,'data': hello}
#     return render(request, 'music/index.html', context)




# # def detail(request,album_id):
# #     return HttpResponse("Album Details")

# def detail(request, album_id):
#     try:
#         album_details = get_object_or_404(Album, pk=album_id)
#     except Album.DoesNotExist:
#         raise Http404("Album does not exist")
#     return render(request, 'music/detail.html', {'album_details': album_details},)




# def favorite(request,album_id):
#     album_details = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album_details.song_set.get(pk=request.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'music/detail.html', {
#             'album_details': album_details,
#             'error_message': "You didn't select a song.",
#         })
#     else:
#         selected_song.is_favorite = True
#         selected_song.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('music:detail', args=(album_details.id,)))    

musicwebsite/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index(request):
    return render(request, 'musicwebsite/index.html')

music/templates/music/album_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

music/templates/music/album_form.html
{% extends 'music/base.html' %} 
{% block title %} Create Album - Music Website  {% endblock %}

{% block body %}
   <div class="container">
       <div class="row">
          
         <div class="col-md-12">
           <div class="container" style="background-color: white;">
            <!-- New Album Form  -->
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include "music/form-template.html" %}
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
           </div>
         </div>

       </div>
   </div>
{% endblock %}

music/templates/music/album_update_form.html
{% extends 'music/base.html' %} 
{% block title %} Create Album - Music Website  {% endblock %}

{% block body %}
   <div class="container">
       <div class="row">
          
         <div class="col-md-12">
           <div class="container" style="background-color: white;">
            <!-- New Album Form  -->
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include "music/form-template.html" %}
                <button type="submit" class="btn btn-primary">Update</button>
              </form>
           </div>
         </div>

       </div>
   </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} Music Website {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href='{% static "music/css/style.css" %}'>
  </head>

<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="/">
          <img  src="https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg" alt="logo" style="width:40px;">
        </a>
        
        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-white" href="/">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'music:index' %}"> <span class="glyphicon glyphicon-music"></span>  ALBUMS </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'music:album_create' %}"><span class="	glyphicon glyphicon-plus"></span> Add Album</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#">LOGIN</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="#">LOGOUT</a>
          </li>
        </ul>
      </nav>
    <br>

    <div class="jumbotron text-center"
        style="background-image: url('https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg');">
        <h1 class="text-center text-info ">Music Website</h1>
        <p class="text-center text-success text-strong">Awesome Music Website Using Django </p>
    </div>
    <hr>

    {% block body %}

    {% endblock %}

    <hr>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-primary text-center">All Right Preserved &copy;FreeToUse </h3>
            </div>
            
        </div>
    </div>

</body>

</html>

music/templates/music/detail.html
 {% extends 'music/base.html' %} 
 {% block title %} Music Website - Details {% endblock %}

 {% block body %}
    <div class="container">
        <div class="row">
           
           <div class="col-md-4">
            <h3 class="text-info">{{ album_details.album_title }} -  Album Details</h3>
            <br>

            <img src="{{ album_details.album_logo }}" width="300px" height="200px" >
           </div>
          <div class="col-md-8">
            <div class="container" style="background-color: white;">
              <h2>Song List</h2>
             <a href=""> <button> Add New Song</button></a>
             <a href=""> <button> View All</button></a>

              <table class="table">
                <thead>
                  <tr>
                    <th>Song Name</th>
                    <th>Artist Name</th>
                    <th>File Type</th>

                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>John</td>
                    <td>Doe</td>
                    <td>john@example.com</td>
                  </tr>
                  <tr>
                    <td>Mary</td>
                    <td>Moe</td>
                    <td>mary@example.com</td>
                  </tr>
                  <tr>
                    <td>July</td>
                    <td>Dooley</td>
                    <td>july@example.com</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

        </div>
    </div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}

<div class="form-group">
    <p class="text-danger">{{ field.errors }}</p>
    <label class="col-sm-2"> {{ field.label_tag }} </label>
    <div class="col-sm-10">{{ field }}</div>
</div>

{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %} 
{% block title %} Music Website - Home Page {% endblock %}
{% block body %}
    

    <div class="container">
        <h3 class="text-info">Music Album List</h3>

        <div class="row">

            {% if latest_album_list %}
            {% for album in latest_album_list %}
            <div class="col-sm-4">

  
                <ul class="list-group">
                   
                    <!-- Implementation Of Namespace -->
                    <li class="list-group-item"><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}
                            <span class="text-success">Produced By</span> {{ album.artist }}
                        <br>
                        <img src="{{ album.album_logo }}" alt="Album Logo" width="300px" height="200px"></a> 
                        </li>

                        <div class="footer">
                            <button><a href="{% url 'music:detail' album.id %}">Details</a></button>
                            <button><a href="{% url 'music:album_delete' album.id %}"><span class="glyphicon glyphicon-trash"></span></a></button>
                            <button><a href="http://"><span class="glyphicon glyphicon-asterisk"></span></a></button>                       
                             <button><a href="{% url 'music:album_update' album.id %}"><span class="glyphicon glyphicon-edit"></span></a></button>


                        </div>
                   
                </ul>
                
            </div>
            {% endfor %}
            
            {% else %}
            <p>No Album List Are Available.</p>
            {% endif %}
        </div>
    </div>

    {% endblock %}

musicwebsite/templates/musicwebsite/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Music Website</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>

<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="/">
          <img  src="https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg" alt="logo" style="width:40px;">
        </a>
        
        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-white" href="/">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'music:index' %}">ALBUM LIST</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#">OTHERS</a>
          </li>
        </ul>
      </nav>
    <br>


    <div class="jumbotron text-center"
        style="background-image: url('https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg');">
        <h1 class="text-center text-info ">Music Website</h1>
        <p class="text-center text-success text-strong">Awesome Music Website Using Django </p>
    </div>
    <hr>

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h3 class="text-info">Music Album List</h3>
                <br>
               Music WEBSITE FROM musicwebsite
            </div>
            <div class="col-sm-6"
                style="background-image: url('https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg');">

            </div>

        </div>
    </div>

    <hr>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-primary text-center">All Right Preserved &copy;FreeToUse </h3>
            </div>
            
        </div>
    </div>

</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Music Website</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    {% load static %}
<link rel="stylesheet" href="{% static "music/images/background.jpg" %}">
  </head>

<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="/">
          <img  src="https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg" alt="logo" style="width:40px;">
        </a>
        
        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-white" href="/">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'music:index' %}">ALBUM LIST</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#">OTHERS</a>
          </li>
        </ul>
      </nav>
    <br>


    <div class="jumbotron text-center"
        style="background-image: url('https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg');">
        <h1 class="text-center text-info ">Music Website</h1>
        <p class="text-center text-success text-strong">Awesome Music Website Using Django </p>
    </div>
    <hr>

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h3 class="text-info">Music Album List</h3>
                <br>
               Music WEBSITE FROM musicwebsite
            </div>
            <div class="col-sm-6"
                style="background-image: url('https://image.shutterstock.com/image-illustration/black-music-notes-on-solid-260nw-154475930.jpg');">

            </div>

        </div>
    </div>

    <hr>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-primary text-center">All Right Preserved &copy;FreeToUse </h3>
            </div>
            
        </div>
    </div>

</body>

</html>